---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-data
  namespace: powerwall
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-cephfs
