apiVersion: 1

datasources:
  - name: InfluxDB (auto provisioned)
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: powerwall
    jsonData:
      dbName: powerwall
      timeInterval: 5s
      httpMode: POST
    editable: true