apiVersion: v1
kind: ConfigMap
metadata:
  name: powerwall-secret
  namespace: powerwall
data:
  email: "user@domain.tld"
  password: "supersecurepass"
  host: "xx.xx.xx.xx"
  pwtz: "America/Chicago"
  timezone: "America/Chicago"
  debug: "no"
  style: "grafana-dark"
