apiVersion: v1
kind: Service
metadata:
  name: pypowerwall
  namespace: powerwall
spec:
  selector:
    app: pypowerwall
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.2.89
  ports:
  - port: 8675
    protocol: TCP
    targetPort: 8675
    name: pypowerwall
  sessionAffinity: None
  type: LoadBalancer
