---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
  namespace: powerwall
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.28.2
          name: telegraf
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config
      volumes:
        - name: config
          configMap:
            name: telegraf
