---

apiVersion: v1
kind: ConfigMap
metadata:
  name: weather411config
  namespace: powerwall
  labels:
    app: weather411
data:
  weather411.conf: |+
    [Weather411]
    DEBUG = no

    [API]
    # Port to listen on for requests (default 8676)
    ENABLE = yes
    PORT = 8676

    [OpenWeatherMap]
    # Register and get APIKEY from OpenWeatherMap.org
    APIKEY = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    # Enter your location in latitude and longitude
    LAT = xxx.xxxx
    LON = yyy.yyyy
    WAIT = 10
    TIMEOUT = 10
    # standard, metric or imperial
    UNITS = metric

    [InfluxDB]
    # Record data in InfluxDB server
    ENABLE = yes
    HOST = influxdb.powerwall
    PORT = 8086
    DB = powerwall
    FIELD = weather
    # Auth - Leave blank if not used
    USERNAME =
    PASSWORD =
    # Influx 2.x - Leave blank if not used
    TOKEN =
    ORG =
    URL =
