apiVersion: v1
kind: Service
metadata:
    name: weather411
    namespace: powerwall
spec:
    externalTrafficPolicy: Local
    ports:
      - name: weather411
        port: 8676
        targetPort: weather411
    selector:
        app: weather411
    type: NodePort
